#!/usr/bin/env bash

mkdir -p /var/log/arpwatch
mkdir -p /usr/share/arpwatch

chown nobody:nogroup /var/log/arpwatch

if [ ! -f /var/lib/arpwatch/arp.dat ]; then
    :> /var/lib/arpwatch/arp.dat    
fi

echo "[✓] Pulling latest ethercodes.db from linuxnet.ca"
curl -L -so /var/lib/arpwatch/ethercodes.db https://linuxnet.ca/ieee/oui/ethercodes.dat
